spring:
  profiles:
    active:
      - dev
---
spring:
  profiles:
    active: dev
  application:
    name: spring-cloud-config-dev
---
spring:
  profiles:
    active: test
  application:
    name: spring-cloud-config-test